### ISSUE TITLE
Improvement to installation instructions

### ISSUE THREAD

**Issue by donquixote2u** [kanishka-linux/hlspy#1]
documentation is well written, but the install instruction "sudo pip3 install pkg_available_in_directory (or pip install pkg_available_in_directory)" could be improved for us literal-minded programmers who try to install a python module called pkg_available_in_directory.

 I would suggest something like "sudo pip3 install {pkg_available_in_directory} (or pip install {pkg_available_in_directory})  where {pkg_available_in_directory} is the exact filename in the 'dist' folder.

**Comment by kanishka-linux** [comment]
I was really thinking something like this might happen. Name of the package may change depending on the version of the program, hence I've written instruction in that way.

However, you've given good suggestion to remove ambiguity. I'll update the README accordingly. Thanks!

**Comment by kanishka-linux** [comment]
Done
