### ISSUE TITLE
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5'

### ISSUE THREAD

**Issue by xaeroborg** [kanishka-linux/hlspy#3]
![image](https://user-images.githubusercontent.com/33274680/63362503-1ec43380-c39c-11e9-9bbf-e80362a3172c.png)

**Steps I took to install**
root@ramya:/home/w3b# **git clone https://github.com/kanishka-linux/hlspy**
Cloning into 'hlspy'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 195 (delta 0), reused 1 (delta 0), pack-reused 191
Receiving objects: 100% (195/195), 61.73 KiB | 196.00 KiB/s, done.
Resolving deltas: 100% (91/91), done.
root@ramya:/home/w3b# **cd hlspy/**
root@ramya:/home/w3b/hlspy# **python3 setup.py sdist**
running sdist
running egg_info
creating hlspy.egg-info
writing hlspy.egg-info/PKG-INFO
writing dependency_links to hlspy.egg-info/dependency_links.txt
writing entry points to hlspy.egg-info/entry_points.txt
writing requirements to hlspy.egg-info/requires.txt
writing top-level names to hlspy.egg-info/top_level.txt
writing manifest file 'hlspy.egg-info/SOURCES.txt'
reading manifest file 'hlspy.egg-info/SOURCES.txt'
writing manifest file 'hlspy.egg-info/SOURCES.txt'
running check
creating hlspy-1.1.1
creating hlspy-1.1.1/hlspy
creating hlspy-1.1.1/hlspy.egg-info
creating hlspy-1.1.1/test
copying files to hlspy-1.1.1...
copying README.md -> hlspy-1.1.1
copying setup.py -> hlspy-1.1.1
copying hlspy/__init__.py -> hlspy-1.1.1/hlspy
copying hlspy/hls.py -> hlspy-1.1.1/hlspy
copying hlspy/netmon.py -> hlspy-1.1.1/hlspy
copying hlspy.egg-info/PKG-INFO -> hlspy-1.1.1/hlspy.egg-info
copying hlspy.egg-info/SOURCES.txt -> hlspy-1.1.1/hlspy.egg-info
copying hlspy.egg-info/dependency_links.txt -> hlspy-1.1.1/hlspy.egg-info
copying hlspy.egg-info/entry_points.txt -> hlspy-1.1.1/hlspy.egg-info
copying hlspy.egg-info/requires.txt -> hlspy-1.1.1/hlspy.egg-info
copying hlspy.egg-info/top_level.txt -> hlspy-1.1.1/hlspy.egg-info
copying test/test.py -> hlspy-1.1.1/test
copying test/test_pdf.py -> hlspy-1.1.1/test
Writing hlspy-1.1.1/setup.cfg
creating dist
Creating tar archive
removing 'hlspy-1.1.1' (and everything under it)
root@ramya:/home/w3b/hlspy# **cd dist/**
root@ramya:/home/w3b/hlspy/dist# **ls**
hlspy-1.1.1.tar.gz
root@ramya:/home/w3b/hlspy/dist# **pip3 install hlspy-1.1.1.tar.gz** 
Processing ./hlspy-1.1.1.tar.gz
Collecting PyQt5 (from hlspy==1.1.1)
  Downloading https://files.pythonhosted.org/packages/85/bd/8a0c863802449f35ad9ca21a1b73190639c206758b4b5e2425617fc99ce9/PyQt5-5.13.0-5.13.0-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl (62.1MB)
    100% |████████████████████████████████| 62.1MB 17kB/s 
Requirement already satisfied: sip in /usr/lib/python3/dist-packages (from hlspy==1.1.1) (4.19.18)
Collecting PyQt5_sip<13,>=4.19.14 (from PyQt5->hlspy==1.1.1)
  Downloading https://files.pythonhosted.org/packages/ec/7d/c8d2326c405cfed1858af83915fa02ba9e9722ae3e0343df0950fd900039/PyQt5_sip-4.19.18-cp37-cp37m-manylinux1_x86_64.whl (67kB)
    100% |████████████████████████████████| 71kB 3.9MB/s 
Building wheels for collected packages: hlspy
  Running setup.py bdist_wheel for hlspy ... done
  Stored in directory: /root/.cache/pip/wheels/af/2d/a8/89689745ecf0dc3157e6216deade7939ee853abf35e1110819
**Successfully built hlspy
Installing collected packages: PyQt5-sip, PyQt5, hlspy
Successfully installed PyQt5-5.13.0 PyQt5-sip-4.19.18 hlspy-1.1.1**
root@ramya:/home/w3b/hlspy/dist# **ls**
hlspy-1.1.1.tar.gz
root@ramya:/home/w3b/hlspy/dist# **hlspy**
Traceback (most recent call last):
  File "/usr/local/bin/hlspy", line 6, in <module>
    from hlspy.__init__ import main
  File "/usr/local/lib/python3.7/dist-packages/hlspy/__init__.py", line 32, in <module>
    from hls import BrowseUrlT
  File "/usr/local/lib/python3.7/dist-packages/hlspy/hls.py", line 29, in <module>
    from PyQt5 import QtCore, QtNetwork, QtWidgets, QtWebEngineWidgets, QtWebEngineCore, QtGui
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/local/lib/python3.7/dist-packages/PyQt5/__init__.py)

**Comment by kanishka-linux** [comment]
QtWebEngine is now separate package and doesn't come with regular PyQt5 installation. 
You've to install it with command

`$ pip3 install PyQtWebEngine`

I'll update the setup.py and installation instructions shortly.

**Comment by xaeroborg** [comment]
It works great. Just to let you know that as I am running Kali Linux where usually the default user is root, hlspy encounters and error that can be overcome with this code appended to the end of every command line `--no-sandbox`

![image](https://user-images.githubusercontent.com/33274680/63449619-ab3d2780-c46a-11e9-8940-f40ec40d2bc1.png)

**Comment by kanishka-linux** [comment]
Updated `setup.py`, so the issue is fixed. 
Normally, I won't recommend using `hlspy` with root user, but still thanks for testing it with `no-sandbox` option.

**Comment by xaeroborg** [comment]
> 
> 
> Updated `setup.py`, so the issue is fixed.
> Normally, I won't recommend using `hlspy` with root user, but still thanks for testing it with `no-sandbox` option.

Thanks for the recommendation I will certainly do so.
