### ISSUE TITLE
Not genuinely headless

### ISSUE THREAD

**Issue by paulie-g** [kanishka-linux/hlspy#4]
This looks fantastic and worked out of the box for me. Unfortunately, it's not quite headless. Running it on a server with no GL and no X, it failed. Is there a way to launch QtWebEngine with the equivalent of chromium's --headless --disable-gpu and/or to otherwise dissuade it from doing anything with graphic output?

**Comment by kanishka-linux** [comment]
one can set env var `QT_QPA_PLATFORM=offscreen`. 
It works, tried on debian bullseye. It doesn't require any code changes on `hlspy` side
```
export QT_QPA_PLATFORM=offscreen
```

It is year old issue, but still may help people looking for solution.

PS: Currently I'm not actively maintaining it, but was quite surprised to see that `hlspy` is still working as expected even after couple of years.
